
name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: This is successful
        id: diff
        run: echo ::set-output name=continue::yes
      - name: This isn't
        run: cat /beep/boop
      - name: This should not run
        run: echo oops
      - name: This should also not run
        if: steps.diff.outputs.continue == 'yes'
        run: echo oops